// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzww-3VkBvX7aqWoS8MV0JKmJCH-G2OJY',
    appId: '1:1034277698420:web:4078c9fe1675eaf4fd4a21',
    messagingSenderId: '1034277698420',
    projectId: 'clone-instagram-8459',
    authDomain: 'clone-instagram-8459.firebaseapp.com',
    databaseURL: 'https://clone-instagram-8459-default-rtdb.firebaseio.com',
    storageBucket: 'clone-instagram-8459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw2k2WQjiB4Ae2r26Vfa0z97KBqmpA0Fo',
    appId: '1:903981267575:ios:4822cf09e5f3a57550e472',
    messagingSenderId: '903981267575',
    projectId: 'fitness-fuel-20731',
    storageBucket: 'fitness-fuel-20731.firebasestorage.app',
    iosBundleId: 'com.example.fitnessfuel',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVHCnwvfmPrAhc9SnbLZjwRntubaCyHTI',
    appId: '1:903981267575:android:5888f734644ec43650e472',
    messagingSenderId: '903981267575',
    projectId: 'fitness-fuel-20731',
    storageBucket: 'fitness-fuel-20731.firebasestorage.app',
  );

}